spring.profiles.active=${SPRING_PROFILE:k8s}
spring.application.name=user-service
spring.config.import=optional:classpath:/config/application-k8s.properties

# Ne pas definir proprietes  ici directement pour garder la logique basee sur les profils
