# Point  dentree vers le profil actif, injecte dynamiquement (default : local)
spring.profiles.active=${SPRING_PROFILE:local}

spring.application.name=user-service

# On importe optionnellement le fichier specif au profil "k8s"
spring.config.import=optional:classpath:/config/application-k8s.properties

