# Point d?entrée vers le profil actif, injecté dynamiquement (par défaut : local)
spring.profiles.active=${SPRING_PROFILE:local}

spring.application.name=user-service

# On importe optionnellement le fichier spécifique au profil "k8s"
spring.config.import=optional:classpath:/config/application-k8s.properties
